site_name: Shuaike Shen's Notebook  #网站名称
site_description: My personal website  #站点描述
site_author: Shuaie Shen   #作者

theme:  #主题
  name: material  #名称
  language: zh    #语言，可设置多套切换
  icon:
    logo: material/library  #默认logo图标
    repo: fontawesome/brands/github-alt
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:  #导航
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-variant-outline
        name: dark mode
      primary: white
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-variant
        name: light mode
      primary: dark
      accent: deep orange
  font:  #字体，false 则阻止从Google加载字体
  # 内置隐私插件自动下载和自托管 Web 字体文件，无需阻止。其他字体使用附加样式表 extra.css 。
    text: Roboto  #常规字体，默认Roboto，正文、标题等，300、400、400i和700
    code: Roboto Mono  #等宽字体，默认Roboto Mono，代码块，400


extra_css:
  - css/basic.css
  - css/admonition.css
  - css/flink.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.css

repo_url: https://github.com/Eurekashen/my-site  #存储库URL

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: custom
      custom_format: "%Y.%m.%d %H:%M:%S %Z"
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - comming_soon.md
        - discussion.md
#  - git-authors:
#      exclude:
#          - index.md
#          - discussion.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Content
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta

extra_javascript:
  # - javascripts/baidu-tongji.js  #百度统计
  - js/mathjax.js  #数学公式的JS
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.js

extra:
#  version: #版本控制
#    provider: mike
#  homepage: https://example.com  #通常logo链接到主页，这里可修改
  social:  #页脚
    - icon: fontawesome/brands/twitter   #社交链接
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter  #一般自动提取
    - icon: fontawesome/solid/paper-plane  #电子邮件
      link: mailto:admin@yiruru.com
#  generator: false  #删除通知“Made with Material for Mk，一般不必
#  analytics: #设置站点分析
#    provider: google
#    property: G-XXXXXXXXXX

nav:
  - Welcome Page: 
    - Welcome Page: index.md
  - Lecture Notes: 
    - notes/index-lecture-notes.md
    - Operating System: 
      # - notes/os/index-os.md
      - Chapter 1 | Introduction: notes/os/notes-os-Chapter-1.md
      - Chapter 2 | Operating-System Structures: notes/os/notes-os-Chapter-2.md
      - Chapter 3 | Processes: notes/os/notes-os-Chapter-3.md
    - Computer Architecture: 
      - notes/com_arch/index-com-arch.md
    - Computer Network: 
      - notes/com_net/index-com-net.md
  - Paper reading: 
    - Welcome Page: paper/index-paper-reading.md
    - Computer Vision: 
      # - paper/index-cv.md
      - AlexNet: paper/cv/paper-reading-alexnet.md
      - CLIP: paper/cv/paper-reading-clip.md
      - MAE: paper/cv/paper-reading-mae.md
      - ResNet: paper/cv/paper-reading-resnet.md
      - ViT: paper/cv/paper-reading-vit.md
    - 3D Vision: 
      # - paper/index-3dv.md
      - NeRF: paper/3dv/paper-reading-nerf.md
    - AI+X: 
      - paper/index-ai-for-sci.md
    - Natural Language Processing: 
      # - paper/index-nlp.md
      - BERT: paper/nlp/paper-reading-bert.md
      - Transformer: paper/nlp/paper-reading-transformer.md
    - Graph: 
      # - paper/index-graph.md
      - GNN: paper/graph/paper-reading-gnn.md
    - Generative Model:  
      # - paper/index-generative.md
      - ControlNet: paper/generative/paper-reading-controlnet.md
      - DallE 2: paper/generative/paper-reading-dalle2.md
      - DDPM: paper/generative/paper-reading-ddpm_ddim.md
      - GAN: paper/generative/paper-reading-gan.md
      - Stable Diffusion: paper/generative/paper-reading-stable_diffusion.md
  - Discussion:
    - Welcome Page: discussion/index-discussion.md
  # - Tools:
  #   - cmake: tools/cmake/tools-cmake.md
  #   - conda: tools/cmake/tools-conda.md
  #   - docker: tools/cmake/tools-docker.md
  #   - git: tools/cmake/tools-git.md
  #   - shell: tools/cmake/tools-shell-linux.md
  # - Programming:
  #   - python: program/python/progamming-python.md
  #   - java: program/python/progamming-java.md